server:
  port: 3000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://localhost:3306/filedb?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
